### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by AlexGodbehere** [olssonm/laravel-backup-shield#10]
Are there plans to update this to Laravel 6.0? It doesn't look like there are any breaking changes, so a simple update to the `composer.json` should suffice.

**Comment by AlexGodbehere** [comment]
I'm getting an out of memory error and I'm not convinced that it's picking up the `config` file. I'll keep investigating.

**Comment by olssonm** [comment]
That seems odd =/ Have you read about the memory limitations under "Important information regarding encryption" in the docs?

What encryption method are your trying to use? And I'm guessing Laravel 6 on PHP7.2?

**Comment by AlexGodbehere** [comment]
Yes, running Laravel 6 on PHP7.2.22. I'm running `ENCRYPTION_WINZIP_AES_256` encryption, but this issue started happening when I realised that I accidentally deleted my `config` file. I've modified the package locally to print out the encryption type being used because when I last had this issue [here](https://github.com/olssonm/laravel-backup-shield/issues/9) the `config` file wasn't being committed. I've just tried to increase the RAM to 2GB but I'm still getting the error, so I'm not sure what's going on here. I'm pretty sure it isn't to do with the package though. Error message below:

```
[deploy@206.189.246.10 -p 1992]: Created zip containing 3158 files. Size is 100.52 MB
[deploy@206.189.246.10 -p 1992]: Applying password and encryption to zip...
[deploy@206.189.246.10 -p 1992]: mmap() failed: [12] Cannot allocate memory
[deploy@206.189.246.10 -p 1992]: mmap() failed: [12] Cannot allocate memory
[deploy@206.189.246.10 -p 1992]: mmap() failed: [12] Cannot allocate memory
[deploy@206.189.246.10 -p 1992]: PHP Fatal error:  Out of memory (allocated 2281476096) (tried to allocate 4294967304 bytes) in 
```

**Comment by olssonm** [comment]
Ah, gotcha.

Yeah, I will still look into improving the code though to minimize the memory usage. On pre PHP 7.2 systems this was very difficult. But since Laravel 6.0 requires PHP 7.2 I might just as well use the bundled methods in PHP. Will look into it and try to release a more efficient version soon.

**Comment by olssonm** [comment]
The latest release ([3.1](https://github.com/olssonm/laravel-backup-shield/releases/tag/v3.1)) now supports the native ZipArchive functions and will use them automatically if the system supports them (i.e. PHP 7.2 and a newer version of the zip-module. 

Might help with the memory usage.

Closing this issue.
