### ISSUE TITLE
setEncryptionIndex Bug?

### ISSUE THREAD

**Issue by HDVinnie** [olssonm/laravel-backup-shield#18]
https://github.com/olssonm/laravel-backup-shield/blob/824f3301174032a316cf3c431dd536871e337411/src/Factories/Password.php#L62

`$zipArchive->setEncryptionIndex($i - 1, $encryption);`

Im getting ZipArchive::setEncryptionIndex(): Argument #2 ($method) must be of type int, string given

**Comment by olssonm** [comment]
@HDVinnie – may I see your config file (please obscure your password) and what version of PHP and Laravel are you using?

What it looks like to me is that you're using a PHP-version that doesn't have the EM-constants available (see here: https://www.php.net/manual/en/zip.constants.php) – or that you have supplied an invalid encryption-key in your `backup-shield.php`-config. 

But get back with the aforementioned info and we'll work it out 😃
