### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by ChrisSantiago82** [olssonm/laravel-backup-shield#22]
Is there a plan to support Laravel 9?

**Comment by olssonm** [comment]
@ChrisSantiago82 Well, I guess that would be possible – but if you're already on Laravel 9, then you have to use `spatie/laravel-backup` version 8 or above. It already supports encryption built in (se the docs: https://spatie.be/docs/laravel-backup/v8/advanced-usage/encrypt-backup-archives), so this package would be superfluous.

Else, get back with your use-case and I'll look into it if it's feasible/necessary.

**Comment by ChrisSantiago82** [comment]
I didn't know that.
Thank you
