### ISSUE TITLE
Composer require failed, using Laravel 5.7 and laravel-backup ^6.0

### ISSUE THREAD

**Issue by chan80** [olssonm/laravel-backup-shield#6]
Hi Marcus,

Encountered this error message when trying to do a composer require:

Problem 1
    - Installation request for spatie/laravel-backup (locked at 6.0.3, required as ^6.0) -> satisfiable by spatie/laravel-backup[6.0.3].
    - Conclusion: don't install spatie/laravel-backup v5.x-dev
    - olssonm/laravel-backup-shield 2.x-dev requires spatie/laravel-backup ~4.0|~5.0 -> satisfiable by spatie/laravel-backup[v4.x-dev, v5.x-dev].
    - olssonm/laravel-backup-shield v2.3 requires spatie/laravel-backup ~4.0|~5.0 -> satisfiable by spatie/laravel-backup[v4.x-dev, v5.x-dev].
    - olssonm/laravel-backup-shield v2.x-dev requires spatie/laravel-backup ~4.0|~5.0 -> satisfiable by spatie/laravel-backup[v4.x-dev, v5.x-dev].
    - Conclusion: don't install spatie/laravel-backup v4.x-dev
    - Installation request for olssonm/laravel-backup-shield ^2.3 -> satisfiable by olssonm/laravel-backup-shield[v2.x-dev, v2.3].

Does this work with laravel-backup v6.x or do I need to install laravel-backup v5.x instead?

Kindly advise. Thanks!

**Comment by olssonm** [comment]
Howdy @chan80! Sorry for the inconvenience, I had missed that there was a new release of `spatie/laravel-backup`.

I've updated for it to work with spatie/laravel-backup 6.0 and released a new version; 2.4 ([link](https://github.com/olssonm/laravel-backup-shield/releases/tag/v2.4)). Feel free to test it out. 

If you have any other issues, just get back to me or else you can close the issue once you've verified it.

**Comment by chan80** [comment]
Hi Marcus! 

Thanks! I am able to install laravel-backup-shield now.
