### ISSUE TITLE
PHP Out of memory issue

### ISSUE THREAD

**Issue by chan80** [olssonm/laravel-backup-shield#7]
Hi Marcus,

When executing php artisan backup:run, it return an out of memory error shown below:

Determining files to backup...
Zipping 378 files...
Created zip containing 378 files. Size is 51.88 MB
Applying password and encryption to zip...
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 1073741832 bytes) 

I'm using ubuntu 16.04 in homestead with php7.2-fpm and I've change my php.ini to the below:
; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit = 2048M

Then, proceeded to restart the fpm and nginx services:
sudo systemctl restart php7.2-fpm
sudo systemctl restart nginx

However, still getting the same out of memory error and the memory size still stays the same as 1073741824 bytes though.

Any idea on this issue?

Kindly advise. Thanks!

**Comment by chan80** [comment]
Just to provide more info:

So I added this line here to increase the memory limit to 3000MB:
    /**
     * ZipCryptoEngine constructor.
     *
     * @param ZipEntry $entry
     */
    public function __construct(ZipEntry $entry)
    {
        ini_set('memory_limit','3000M');
        $this->entry = $entry;
    }

Still getting the same error though:

Determining files to backup...
Zipping 378 files...
Created zip containing 378 files. Size is 51.88 MB
Applying password and encryption to zip...
PHP Fatal error:  Allowed memory size of 3145728000 bytes exhausted (tried to allocate 2147483656 bytes) in /home/vagrant/code/webapp/vendor/nelexa/zip/src/PhpZip/Crypto/TraditionalPkwareEncryptionEngine.php on line 214

   Symfony\Component\Debug\Exception\FatalErrorException  : Allowed memory size of 3145728000 bytes exhausted (tried to allocate 2147483656 bytes)

My free -m looks something like this:
              total        used        free      shared  buff/cache   available
Mem:           2000         345        1257          51         397        1442
Swap:          1023           0        1023

Can the ZipCrytoEngine use the swap file as well or it must be pure memory?

Weird part is my compressed zip file is only 51.88MB... how come it uses more than 1GB of RAM... is this behaviour expected?

**Comment by olssonm** [comment]
Yes, using ZipCrypto is very memory-intensive. 

But for a 51MB-file it shouldn't use that much memory (I've zipped files of several 100MB without any issues on a machine with 512MB of RAM). However, all files need to be in memory to perform the encryption.

Does the other compression algorithms yield the same results; for instance AES 256?

As long as your swap-file is correctly setup, the OS should automatically use it when needed – shouldn't have to be real physical RAM.

**Comment by olssonm** [comment]
@chan80 Have you had any luck? =)

**Comment by chan80** [comment]
Hi Marcus,

Couldn't get it to work, so I ended up reverting to the old school approach of writing a linux script calling the awscli to remote backup to aws s3 via cron jobs instead.

Thanks for the follow-up.

Cheers,
Chan

**Comment by HDVinnie** [comment]
@chan80

Search "memory_limit" in your php.ini, and change the value of it. 
If no "memory_limit" found, add the following line at the end of php.ini

memory_limit = 1024M ; /* Change the 128M to your needs */

Save file.
